[package]
name = "hue-mqtt"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
config = "0.13.3"
derive_builder = "0.12.0"
eventsource-client = "0.11.0"
eyre = "0.6.8"
futures = "0.3.28"
hyper = { version = "0.14.27", features = ["full"] }
hyper-rustls = "0.24.1"
palette = { version = "0.7.2", features = ["serializing"] }
rand = "0.8.5"
rumqttc = "0.22.0"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
serde_path_to_error = "0.1.14"
tokio = { version = "1.29.1", features = ["macros", "full"] }
tokio-rustls = { version = "0.24.1", features = ["dangerous_configuration"] }
